### ISSUE TITLE
Error while trying to add resources (i believe)

### ISSUE THREAD

**Issue by horizontech-dev** [HorizonTechnologies/Zapp#11]
[2020-08-12 04:39:54,291] ERROR in app: Exception on /slack/message_actions [POST]
Traceback (most recent call last):
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/Zbot/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/admin/Zbot/main.py", line 274, in _message_actions
    progress.report(user_id, channel_id, slack_client)
  File "/home/admin/Zbot/progress.py", line 74, in report
    report = show(user)
  File "/home/admin/Zbot/progress.py", line 42, in show
    cursor.execute(query, (user, datetoday, ))
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

**Comment by horizontech-dev** [comment]
basically unable to add new resources.
